# Loader Metadata
modLoader = "javafml"
loaderVersion = "[44,)"
license = "MIT"
issueTrackerURL = "https://github.com/alcatrazEscapee/cyanide/issues"

[[mods]]
    modId = "cyanide"
    version = "${file.jarVersion}"
    displayName = "Cyanide"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/cyanide-forge"
    authors = "AlcatrazEscapee"
    description = "A mod which substantially improves Minecraft's data driven world generation error detection and recovery mechanisms."

[[dependencies.cyanide]]
    modId = "forge"
    mandatory = true
    versionRange = "[44,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.cyanide]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.3,)"
    ordering = "NONE"
    side = "BOTH"
