# Loader Metadata
modLoader = "javafml" # mandatory
loaderVersion = "[41,)" # mandatory
license = "MIT"
issueTrackerURL = "https://github.com/alcatrazEscapee/primal-winter/issues" # optional

[[mods]] # mandatory
    modId = "cyanide" # mandatory
    version = "${file.jarVersion}" # mandatory
    displayName = "Cyanide" # mandatory
    #updateJSONURL="http://myurl.me/" #optional
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/cyanide-forge" #optional
    #logoFile="examplemod.png" #optional
    #credits="" #optional
    authors = "AlcatrazEscapee" #optional
    description = '''
        A horrible accident has left the world - the entire world - a frozen wasteland. Unending snowstorms rage across the land, from forests, to plains, to jungles, to deserts. The air is thick with fog and wind howls across the landscape. Will you be able to survive in this primordial winter?
        '''

[[dependencies.cyanide]]
    modId = "forge"
    mandatory = true
    versionRange = "[41,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.cyanide]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19,)"
    ordering = "NONE"
    side = "BOTH"
