# Mod
modName=Cyanide
modAuthor=AlcatrazEscapee
modId=cyanide
modGroup=com.alcatrazescapee
modIssueUrl=https://github.com/alcatrazEscapee/cyanide/issues
modSourceUrl=https://github.com/alcatrazEscapee/cyanide
modHomeUrl=https://www.curseforge.com/minecraft/mc-mods/cyanide
modDescription=A mod which substantially improves Minecraft's data driven world generation error detection and recovery mechanisms.

modJavaVersion=21

# Versions
minecraftVersion=1.21.1
minecraftVersionRange=[1.21.1,1.21.2)

parchmentVersion=2024.07.28
parchmentMinecraftVersion=1.21

neoForgeVersion=21.1.36
neoForgeVersionRange=[4,)

modNeoFormVersion=1.21-20240613.152323
modManifoldVersion=2024.1.34-20241001.011431-2

fabricVersion=0.103.0+1.21.1
fabricVersionRange=*
fabricLoaderVersion=0.15.11
fabricLoaderVersionRange=[0.15,)

epsilonVersion=0.6

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false