# Mod
modName=Cyanide
modAuthor=AlcatrazEscapee
modId=cyanide
modGroup=com.alcatrazescapee
modIssueUrl=https://github.com/alcatrazEscapee/cyanide/issues
modSourceUrl=https://github.com/alcatrazEscapee/cyanide
modHomeUrl=https://www.curseforge.com/minecraft/mc-mods/cyanide
modDescription=A mod which substantially improves Minecraft's data driven world generation error detection and recovery mechanisms.

modJavaVersion=21

# Versions
minecraftVersion=1.21.4
minecraftVersionRange=[1.21.4]

parchmentVersion=2025.03.23
parchmentMinecraftVersion=1.21.4

neoForgeVersion=21.4.124
neoForgeVersionRange=[4,)

modNeoFormVersion=1.21.4-20241203.161809
modManifoldVersion=2025.1.10

fabricVersion=0.119.2+1.21.4
fabricVersionRange=*
fabricLoaderVersion=0.16.13
fabricLoaderVersionRange=[0.16,)

epsilonVersion=0.6

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false