@MethodsReturnNonnullByDefault
@FieldsAreNonnullByDefault
package com.alcatrazescapee.cyanide.codec;

import net.minecraft.FieldsAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;